on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          retention-days: 5
      - name: Deploy
        run: |
          curl https://${{ env.WORDPRESS_URL_API }}/${{github.repository}}/${{github.ref_name}}/${{github.run_id}};